// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OutboxEvent struct {
	ID            int64              `json:"id"`
	EventID       pgtype.UUID        `json:"event_id"`
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   int64              `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
	Status        string             `json:"status"`
	RetryCount    int32              `json:"retry_count"`
	CorrelationID pgtype.UUID        `json:"correlation_id"`
	CausationID   pgtype.UUID        `json:"causation_id"`
}

type Product struct {
	ID            int64              `json:"id"`
	Sku           string             `json:"sku"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	CategoryID    int64              `json:"category_id"`
	Brand         string             `json:"brand"`
	PriceAmount   int64              `json:"price_amount"`
	PriceCurrency string             `json:"price_currency"`
	Stock         int32              `json:"stock"`
	IsActive      bool               `json:"is_active"`
	Attributes    []byte             `json:"attributes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
