// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID            int64              `json:"id"`
	Sku           string             `json:"sku"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	CategoryID    int64              `json:"category_id"`
	Brand         string             `json:"brand"`
	PriceAmount   int64              `json:"price_amount"`
	PriceCurrency string             `json:"price_currency"`
	Stock         int32              `json:"stock"`
	IsActive      bool               `json:"is_active"`
	Attributes    []byte             `json:"attributes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
