// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUnprocessedOutboxEvents = `-- name: GetUnprocessedOutboxEvents :many
SELECT id, event_id, event_type, aggregate_type, aggregate_id, payload, occurred_at, processed_at, status, retry_count, correlation_id, causation_id FROM outbox_events WHERE status = 'pending' LIMIT $1 FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetUnprocessedOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getUnprocessedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.OccurredAt,
			&i.ProcessedAt,
			&i.Status,
			&i.RetryCount,
			&i.CorrelationID,
			&i.CausationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementRetryCount = `-- name: IncrementRetryCount :exec
UPDATE outbox_events SET retry_count = retry_count + 1 WHERE id = $1 and status = 'pending'
`

func (q *Queries) IncrementRetryCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementRetryCount, id)
	return err
}

const markEventsAsProcessing = `-- name: MarkEventsAsProcessing :exec
UPDATE outbox_events SET status = 'processing' WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkEventsAsProcessing(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, markEventsAsProcessing, dollar_1)
	return err
}

const markProcessedOutboxEvent = `-- name: MarkProcessedOutboxEvent :exec
UPDATE outbox_events SET status = 'done', processed_at = now() WHERE id = $1
`

func (q *Queries) MarkProcessedOutboxEvent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markProcessedOutboxEvent, id)
	return err
}

const saveOutboxEvent = `-- name: SaveOutboxEvent :exec
INSERT INTO outbox_events (
    event_id,
    event_type,
    aggregate_type,
    aggregate_id,
    payload,
    occurred_at,
    processed_at,
    retry_count,
    correlation_id,
    causation_id,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'pending')
`

type SaveOutboxEventParams struct {
	EventID       pgtype.UUID        `json:"event_id"`
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   int64              `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
	RetryCount    int32              `json:"retry_count"`
	CorrelationID pgtype.UUID        `json:"correlation_id"`
	CausationID   pgtype.UUID        `json:"causation_id"`
}

func (q *Queries) SaveOutboxEvent(ctx context.Context, arg SaveOutboxEventParams) error {
	_, err := q.db.Exec(ctx, saveOutboxEvent,
		arg.EventID,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
		arg.OccurredAt,
		arg.ProcessedAt,
		arg.RetryCount,
		arg.CorrelationID,
		arg.CausationID,
	)
	return err
}
