// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    sku,
    name,
    description,
    price_amount,
    price_currency,
    stock,
    is_active,
    attributes,
    category_id,
    brand
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id
`

type CreateProductParams struct {
	Sku           string      `json:"sku"`
	Name          string      `json:"name"`
	Description   pgtype.Text `json:"description"`
	PriceAmount   int64       `json:"price_amount"`
	PriceCurrency string      `json:"price_currency"`
	Stock         int32       `json:"stock"`
	IsActive      bool        `json:"is_active"`
	Attributes    []byte      `json:"attributes"`
	CategoryID    int64       `json:"category_id"`
	Brand         string      `json:"brand"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.PriceAmount,
		arg.PriceCurrency,
		arg.Stock,
		arg.IsActive,
		arg.Attributes,
		arg.CategoryID,
		arg.Brand,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, sku, name, description, category_id, brand, price_amount, price_currency, stock, is_active, attributes, created_at, updated_at FROM products WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.Brand,
		&i.PriceAmount,
		&i.PriceCurrency,
		&i.Stock,
		&i.IsActive,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
