// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error)
	GetProductByID(ctx context.Context, id int64) (Product, error)
	GetProductForReadModel(ctx context.Context, id int64) (GetProductForReadModelRow, error)
	GetUnprocessedOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	IncrementRetryCount(ctx context.Context, id int64) error
	MarkEventsAsProcessing(ctx context.Context, dollar_1 []int64) error
	MarkProcessedOutboxEvent(ctx context.Context, id int64) error
	SaveOutboxEvent(ctx context.Context, arg SaveOutboxEventParams) error
}

var _ Querier = (*Queries)(nil)
