// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error)
	GetProductByID(ctx context.Context, id int64) (Product, error)
	GetUnprocessedOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	MarkProcessedOutboxEvent(ctx context.Context, arg MarkProcessedOutboxEventParams) error
	SaveOutboxEvent(ctx context.Context, arg SaveOutboxEventParams) error
}

var _ Querier = (*Queries)(nil)
