// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error)
	GetProductByID(ctx context.Context, id int64) (Product, error)
}

var _ Querier = (*Queries)(nil)
